# Module 3 Exercises (Arrays) (2)
Please use Module 3 and online references to complete the following exercises. 

In [13]:
# import numpy - this is the last time we will tell you explicitly to import numpy. 
import numpy as np

## Exercise 1
(a) Create a variable `totalNum` and set its value to 10. Then create a list of `totalNum` (=10 here) random numbers in the range of `[0,1)`. (The value of totalNum will be changed later.) Print the list.

(b) Change the signs of all the numbers with odd indexes in the list. Print the list again.

(c) Print the first 6 elements in the list.

(d) Print the last 6 elements in the list.

(e) Find the mean and the standard deviation of the list. (Please look up the NumPy commands for mean and standard deviation if you are not familiar with them.)

(f) Modify your code in parts (a) so that the list now contains 1000 random numbers. (You may want to comment out the print statements in parts (a) and (b) for this part.) Re-run parts (a-e). Is the mean close to your expectation? 

**Note:** This is something we do frequently in coding. We write some code using a short list to make sure that everything is working properly by using print statements. We then switch to a much longer list by changing one line of code near the top and comment out the print statements that we no longer need. 

**Good coding practice:** Create variable names for all quantities in the main part of the code, and assign numerical values to these variables at beginning part of the code.

In [28]:
# Exercise 1(a). Create a variable totalNum and set its value to 10.
# Create a list of totalNum (=10) random numbers in the range of [0,1). 
# Print the list.

totalNum=100
num=np.random.rand(totalNum)

num2=num.copy()
print(num2)

num2[::2]*=-1

print(num2)

[0.01285243 0.5761494  0.76667523 0.89634831 0.41489373 0.57159051
 0.54604798 0.95739097 0.68244703 0.58357799 0.01432298 0.37043755
 0.17678929 0.74815656 0.93007021 0.95420419 0.66400625 0.85962281
 0.01833077 0.55768752 0.45871784 0.18941717 0.37520169 0.41122223
 0.85068615 0.02630485 0.10216959 0.79649596 0.20692269 0.48297832
 0.25516256 0.72146964 0.3827332  0.83666398 0.04961522 0.14136313
 0.90077069 0.40500318 0.36698979 0.56837377 0.78818794 0.18158208
 0.04106256 0.14225343 0.98419401 0.99132962 0.22053705 0.18863012
 0.40112376 0.01351497 0.89020886 0.80827934 0.03527507 0.17439989
 0.77733783 0.54494861 0.91772144 0.39172772 0.49313755 0.54714954
 0.04745599 0.40849154 0.19803309 0.58217278 0.57670821 0.37632774
 0.45113381 0.57919374 0.95869754 0.64403113 0.2030588  0.45425907
 0.06438845 0.31556738 0.06026963 0.95311675 0.21440552 0.67254324
 0.52835243 0.65436825 0.24634142 0.09493054 0.97865847 0.78351895
 0.39972878 0.25771126 0.39865615 0.8073435  0.80956545 0.5940

In [29]:
# Exercise 1(b).  Change the signs of all the numbers with odd indexes in the list. Print the list again.
num2=num.copy()
print(num2)

num2[::2]*=-1

print(num2)

[0.01285243 0.5761494  0.76667523 0.89634831 0.41489373 0.57159051
 0.54604798 0.95739097 0.68244703 0.58357799 0.01432298 0.37043755
 0.17678929 0.74815656 0.93007021 0.95420419 0.66400625 0.85962281
 0.01833077 0.55768752 0.45871784 0.18941717 0.37520169 0.41122223
 0.85068615 0.02630485 0.10216959 0.79649596 0.20692269 0.48297832
 0.25516256 0.72146964 0.3827332  0.83666398 0.04961522 0.14136313
 0.90077069 0.40500318 0.36698979 0.56837377 0.78818794 0.18158208
 0.04106256 0.14225343 0.98419401 0.99132962 0.22053705 0.18863012
 0.40112376 0.01351497 0.89020886 0.80827934 0.03527507 0.17439989
 0.77733783 0.54494861 0.91772144 0.39172772 0.49313755 0.54714954
 0.04745599 0.40849154 0.19803309 0.58217278 0.57670821 0.37632774
 0.45113381 0.57919374 0.95869754 0.64403113 0.2030588  0.45425907
 0.06438845 0.31556738 0.06026963 0.95311675 0.21440552 0.67254324
 0.52835243 0.65436825 0.24634142 0.09493054 0.97865847 0.78351895
 0.39972878 0.25771126 0.39865615 0.8073435  0.80956545 0.5940

In [22]:
# Exercise 1(c). Print the first 6 elements in the list.
print(num2[:6])

[-0.08470772  0.76551582 -0.00332604  0.90014625 -0.47465628  0.49428576]


In [26]:
# Exercise 1(d). Print the last 6 elements in the list.
print(num2[-6:])

[-0.47465628  0.49428576 -0.42811211  0.83228494 -0.47785195  0.1875646 ]


In [30]:
# Exercise 1(e). Find the mean and the standard deviation of the list. 
standard = np.std(num2)
print(standard)

mean = np.mean(num2)
print(mean)


0.5696201322716149
0.04264888890195517


Exercise 1(f) Modify your code in parts (a) so that the list now contains 1000 random numbers. (You may want to comment out the print statements in parts (a) and (b) for this part.) Re-run parts (a-e). Is the mean close to your expectation?


## Exercise 2
In Module 3, we learned how to concatenate two lists together to form a single list by using the `np.hstack` command. There is another command — **`np.concatenate`** — that can perform the same task, but with a slight variation. Please look up `np.concatenate` online and use it to complete the following tasks:

In [33]:
# Exercise 2(a). Use np.concatenate to concatenate the lists myZeros and myOnes below. 
# Print the concatenated list.

myZeros = np.zeros(3)       #create a list of 3 zeros
myOnes = np.ones(5)         #create a list of 5 ones

np.concatenate((myZeros,myOnes))
print(np.concatenate((myZeros,myOnes)))

[0. 0. 0. 1. 1. 1. 1. 1.]


In [42]:
#Sorry I accidently cut this part out

print(np.concatenate((myZeros,[22])))

[ 0.  0.  0. 22.]


Part (c): Comment on the similarities and the differences between np.concatenate and np.hstack.


In [ ]:
#for 1-D arrays it concatenates along the first axis

## Exercise 3
The cell below contains a Python list (not a NumPy list) of names of all students in our class. The goal is to print random groups of two students per group. (Each student's name should only appear once, of course.) 

**Please plan and discuss strategy with your group members on the whiteboard before you start to code.**

**Hint**: The NumPy command `np.random.shuffle` may be helpful for this task. Please look it up.

In [58]:
# Exercise 3
import random

Names = ['Nina','Ceiligh','Dani','Soo','Treya','Zoë']

arr = np.array(Names)

names2=arr.reshape(3,2)
print(names2)


random.shuffle(names2)

print(names2)




[['Nina' 'Ceiligh']
 ['Dani' 'Soo']
 ['Treya' 'Zoë']]
[['Nina' 'Ceiligh']
 ['Nina' 'Ceiligh']
 ['Dani' 'Soo']]


## Exercise 4 (Optional)
If you have studied linear algebra and would like to explore matrix operations with NumPy, please try this exercise.


In [20]:
# Exercise 4a. Create a row vector of 3 elements with values of 1, 2, and 3, respectively. Call this rowVector 
#and print it to screen.


In [21]:
# Exercise 4b. Create a column vector of that is the transpose of rowVector. Call this colVector and print it to 
#screen. (Please look up the NumPy command for the transpose operation.)


In [22]:
# Exercise 4c. Print the return of np.dot(rowVector, colVector) to screen. Does the result agree with your 
#expectation?


In [18]:
# Exercise 4d. Print the return of np.dot(colVector, rowVector) to screen. Does the result agree with your 
#expectation?


Exercise 4e: If you attempt to do rowVector*rowVector or colVector*colVector, Python is perfectly happy to do it for you. If, however, you attemp to do np.dot(rowVector, rowVector) or np.dot(colVector, colVector), you will get an error message. Why? What is the difference between these two types of multiplication (np.dot and *)?