# Module 3 Exercises (Arrays) (1)
Please use Module 3 and online references to complete the following exercises. Before you start, type in the code to load the NumPy library.

In [1]:
# import numpy
import numpy as np

### Exercise 1
This exercise is almost identical to Exercise 1 in Module 2, except we will use a **NumPy list**, as opposed to a regular Python list. You will find that the commands from the previous lab don't all work here, because NumPy lists are different from regular Python lists. We encourage you to use **Google** to explore how to complete these tasks if the commands from Module 2 don't work. 

Write computer code in the cell below to complete the following tasks. Please print the result of each step to screen.

(a) Create a **NumPy list** of elements with numerical values of 5, 3, 6, 1 and 8, and name it `myNumPyList`.

(b) Make a copy of `myNumPyList` and give it a **new name**.

(c) Update `myNumPyList` by making the second element in the list 7 times as large.

(d) Update `myNumPyList` again by adding 10 to the last element in the list.

(e) Update `myNumPyList` again by reversing the order of the elements.

(f) Update `myNumPyList` again by removing the first element from the list.

(g) Print the copy of `myNumPyList` from part (b) to see if it has been affected by parts (c) to (f). If it has been affected, please change your code for part (b) so that your copy is a true copy.

In [15]:
# Exercise 1(a): Create a NumPy list of elements with numerical values of 5, 3, 6, 1 and 8,

myNumPyList=[5,3,6,1,8]
newNumPyList=myNumPyList.copy()
myNumPyList[1]=myNumPyList[1]*7
myNumPyList[-1]=myNumPyList[-1]+10
myNumPyList=np.flip(myNumPyList)
myNumPyList=np.delete(myNumPyList,0)
print(newNumPyList)
print(myNumPyList)

[5, 3, 6, 1, 8]
[ 1  6 21  5]


In [16]:
# Exercise 1(b): Make a copy of myNumPyList
newNumPyList=myNumPyList.copy()

In [17]:
# Exercise 1(c): Update myNumPyList by making the second element in the list 7 times as large.
myNumPyList[1]=myNumPyList[1]*7

In [18]:
# Exercise 1(d): Update myNumPyList again by adding 10 to the last element in the list.
myNumPyList[-1]=myNumPyList[-1]+10

In [19]:
# Exercise 1(e): Update myNumPyList again by reversing the order of the elements.
myNumPyList=np.flip(myNumPyList)

In [20]:
# Exercise 1(f): Update myNumPyList again by removing the first element from the list.
myNumPyList=np.delete(myNumPyList,0)

In [21]:
# Exercise 1(g): Print the copy of `myNumPyList` from part (b) to see if it has been affected by parts (c) to (f). 
# If it has been affected, please change your code for part (b) so that your copy is a true copy.
myNumPyList=np.delete(myNumPyList,0)

### Exercise 2
Write computer code in the cell below to complete the following tasks.

(a) Use two different commands — **`np.arange`** and **`np.linspace`** — to create a regular list of integers from 1 to 25 with an increment of 1. How many elements are there in the list? (Hint: Use a Python command.)

(b) Use two different commands — **`np.arange`** and **`np.linspace`** — to create  a regular list of integers from 1 to 25 with an increment of 4. How many elements are there in the list? (Hint: Use a Python command.)

(c) Create a list of numbers in the range of `[0.25, 1.33)` with an increment of 0.22. How many elements are there in the list? (Use the most convenient command to create your list.)

(d) Repeat the previous task except the numbers in the list go backwards from 0.25 towards -1.33. 

(e) Comment on the similarities and the differences between **`np.arange`** and **`np.linspace`**.

In [32]:
# Exercise 2(a): Use two different commands — np.arange and np.linspace - create a regular list of integers 
#from 1 to 25 with an increment of 1. How many elements are there in the list?

num=np.arange(1,26,1)
print(num)
print(len(num))
lin=np.linspace(1,25,25)
print(lin)
print(len(lin))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
25
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25.]
25


In [39]:
# Exercise 2(b): Use two different commands — np.arange and np.linspace - create a regular list of integers 
#from 1 to 25 with an increment of 4. How many elements are there in the list?
num2=np.arange(1,26,4)
print(num2)
print(len(num2))
lin2=np.linspace(1,25,7)
print(lin2)
print(len(lin2))

[ 1  5  9 13 17 21 25]
7
[ 1.  5.  9. 13. 17. 21. 25.]
7


In [51]:
# Exercise 2(c)&(d):
num3=np.arange(0.25,1.33,0.22)
print(num3)
print(len(num3))
lin3=np.linspace(0.25,1.33,5)
print(lin3)

#linspace is more useful when you want exact spacing and a specific length in mind for a list
#arange is a lot more straight forward as you can just put in the increment you desire

[0.25 0.47 0.69 0.91 1.13]
5
[0.25 0.52 0.79 1.06 1.33]


Comments (Part (e)):



### Exercise 3
The $x$-coordinate of an object is given by the following equation:

$$x(t)= t^2-2t+3,\ \ \ \ \ \ \ \ \ \ \ \ \ \  (1)$$

where $t$ is time. 

(a) Create a list for `t` from `[0,3]` (include 3) with an increment of 0.2, and create the corresponding list for `x` using Eq. (1). Print both lists to screen.

(b) Find the value of $x(2)$, and comment on the difference in the meanings between $x(2)$ and `x[2]`. 

(c) Use the command `np.min` to find the smallest element in `x`. Examine the printed lists of `t` and `x` to find at what value of `t` when `x` is minimum. (**Optional**) If you want more challenge, try to find online how the command `np.where` works and write computer code to do the last part of the task (finding the value of `t` when `x` is minimum).  

In [70]:
# Exercise 3
t=np.arange(0,3.1,0.2)

x=t**2-2*t+3
print(x)
print(t)
print(x[2])
#x(2) would throw an error because an array is no callable

print(np.min(x))
#when t=1, x is at its min, 2


[3.   2.64 2.36 2.16 2.04 2.   2.04 2.16 2.36 2.64 3.   3.44 3.96 4.56
 5.24 6.  ]
[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3. ]
2.36
2.0


Part (b) comments: